# Generated by Django 5.2.3 on 2025-06-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_club', models.CharField(max_length=100)),
                ('codigo_club', models.CharField(max_length=10)),
                ('usuario_twitter', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_torneo', models.CharField(max_length=100)),
                ('empresa_auspiciante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=100)),
                ('rol_juego', models.CharField(max_length=30)),
                ('dorsal', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('club_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.club')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField()),
                ('club_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.club')),
                ('torneo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.torneo')),
            ],
        ),
    ]
